apiVersion: v1
kind: Pod
spec:
  containers:
    - name: terraform
      image: docker.io/vmartinvega/bootcamp-terraform:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: IfNotPresent
      env:
        - name: TF_REGISTRY_CLIENT_TIMEOUT
          value: 20
      volumeMounts:
        - name: terraform-volume
          mountPath: /home/terraform
  volumes:
    - name: terraform-volume
      persistentVolumeClaim:
        claimName: terraform-volume
